# Chartered Organization Representative {-}

## What does this mean? {-}

The Chartered Organization Representative (COR) is the vital link between a Scouting unit and its sponsoring organization (e.g., church, school, or community group). 

## What do I do? {-}

Key responsibilities of the COR include:

- **Liaison Duties:** Acting as the primary communication bridge between the Scouting unit, the chartered organization, and the local Scouting district/council.
- **Leadership & Support:** Serving on the unit "Key 3" team (with the committee chair and unit leader) and appointing the unit committee chair.
- **Approving Personnel:** Reviewing and approving all adult volunteer applications for the unit. This also includes that all volunteers are fully trained for thier position.
- **Representation:** Serving as a voting member of the local council and district committee.
- **Unit Success:** Ensuring the unit maintains high-quality programs, active membership recruitment, and follows Scouting America policies.

## Do I need to be registered? {-}

Yes! 

## Do I need to be trained? {-}

Yes!

The online training module take ~45 minutes. 

[Click HERE to take Chartered Organization Representative Training](https://training.scouting.org/learning-plans/1016)

::: {.callout-note}
If you do not already have a my.scouting account, you will be able to create one.
:::

This training focuses on the following topics:

- What is a Charter?
- Scouting Units
- The COR Position
- Standards and Volunteers

Scouting America has compiled more information in the [Chartered Organization Rpresentative Guidebook](https://filestore.scouting.org/filestore/pdf/511-421(16)_web.pdf)

