# Cub Scouts {-}

View [training requirements (external link)](https://www.scouting.org/wp-content/uploads/2025/10/Position-Trained-Requirements-Oct2025.pdf) for your specific position.

First, go to another Browser tab, log on to [https://my.scouting.org/](https://my.scouting.org/)

Then come back here and click on the links below to directly go to that training module.

## Cubmaster and Assistant Cubmaster

  - [Cubmaster and Assistant Cubmaster Position Specific Training](https://training.scouting.org/learning-plans/1051)
  - [Hazardous Weather Training](https://training.scouting.org/courses/SCO_800) 
  - **Basic Adult Leader Outdoor Orientation (BALOO) ** 
    - In-Person Only
    - For the next offering, contact your council

## Den Leader and Assistant Den Leader

  - [Den Leader and Assistant Den Leader Position Specific Training](https://training.scouting.org/learning-plans/1055)
  - [Hazardous Weather Training](https://training.scouting.org/courses/SCO_800) 

## Pack Committee Chair

  - [Pack Committee Chair Position Specific Training](https://training.scouting.org/learning-plans/1059)

## Pack Committee Member

  - [Pack Committee Member Position Specific Training](https://training.scouting.org/learning-plans/1059)
  
## New Members Coordinator

  - [New Member Coordinator Training](https://training.scouting.org/learning-plans/1128)