# Merit Badge Counselor {-}

## What do I do? {-}

A merit badge counselor is a responsible adult with knowledge and enthusiasm about a career, hobby or other subject who is willing to share that knowledge and enthusiasm with Scouts.

Find out more about [Merit Badge Counselors](https://www.scouting.org/merit-badge-tips-guide/merit-badge-counselor/) at Scouting America's National Website. 

## How do I get involved? {-}

Talk with the Scoutmaster or Committee Chair of the Scouting Unit at your sponsoring organization, or reach out to your local council office. In this area, check out the [Juniata Valley Council](https://www.jvcscouting.org/staff-directory/) contact list.

### Register {-}

Contact your local council office to register as a merit badge counselor.

### Get Trained {-}

Yes. Merit Badge Counselors are required to take:

- [Safeguarding Youth Training](https://training.scouting.org/courses/SCO_3014) 
- [Merit Badge Counselor Training](https://training.scouting.org/learning-plans/1188)
