# Upcoming Events {-}

## Basic Adult Leader Outdoor Orientation (BALOO) {-}
- When: Saturday October 10-11, 2026
- Where: Seven Mountains Scout Camp
- Registration: [https://scoutingevent.com/497-116672](https://scoutingevent.com/497-116672)

## Introduction to Outdoor Leader Skills (IOLS) {-}
- When: Saturday October 10-11, 2026
- Where: Seven Mountains Scout Camp
- Registration: [https://scoutingevent.com/497-116674](https://scoutingevent.com/497-116674)

## Range & Target Activities (RATA) {-}
- When: Friday November 20-21, 2026
- Where: Seven Mountains Scout Camp
- Registration: Coming Soon

## Supplemental Adult Scout Skills (SASS) {-}
- When: Saturday February 20, 2027
- Where: Our Lady of Victory Activities Center, 820 Westerly Parkway, State College, PA 16801 
- Registration: Coming Soon

## University of Scouting {-}
- When: Saturday February 27, 2027
- Where: Camp Karoondinha, Susquehanna Council
- Registration: Not Yet Available

## Basic Adult Leader Outdoor Orientation (BALOO) {-}
- When: Friday April 23-24, 2027 
- Where: Seven Mountains Scout Camp
- Registration: Coming Soon

## Introduction to Outdoor Leader Skills (IOLS {-}
- When: Friday April 23-24, 2027
- Where: Seven Mountains Scout Camp
- Registration: Coming Soon

## Wilderness First Aid (WFA) {-}
- When: Saturday May 15-16, 2027
- Where: Seven Mountains Scout Camp
- Registration: [https://scoutingevent.com/497-116563](https://scoutingevent.com/497-116563)

## National Youth Leadership Training (NYLT) {-}
- When: June 6-12, 2027
- Where: Camp Karoondinha, Susquehanna Council
- Registration: Coming Soon

# National Scouting Event Calendar {-} 

## Wood Badge Across the Nation {-}

[Nationwide Wood Badge Offerings](https://scoutingevent.com/Global?page=1&calendarType=1&printCalendar=0&printCalendarMonths=1&searchterm=wood+badge&filter-date-min=&filter-date-max=&filter-country=232&filter-zipcode=&filter-distance=100&filter-state=0) are updated regularly. Please keep in mind that it is up to each council to add their offering to this national list.

## National Youth Leadership Training (NYLT) Across the Nation {-}

[Nationwide NYLT Offerings](https://scoutingevent.com/Global?page=1&calendarType=1&printCalendar=0&printCalendarMonths=1&searchterm=nylt&filter-date-min=&filter-date-max=&filter-country=232&filter-zipcode=&filter-distance=100&filter-state=0) are updated regularly. Please keep in mind that it is up to each council to add their offering to this national list.


