# Become a Trained Leader

There is required training for all of those in any kind of leadership position like Council President, Cubmasters/Scoutmasters, Merit Badge Counselors, Chartering Organization Representatives, Youth leaders of National Youth Leadership Prgram, and more!

## Why do you ask?

Because a trained leader can do their job easier 


# Required Training {-}

View [training requirements](https://www.scouting.org/wp-content/uploads/2025/10/Position-Trained-Requirements-Oct2025.pdf) for your specific position.

::: {.callout-note}
If you are having problems completing your training try the following:
- be sure you have a strong internet connection
- switch your device to a **computer** and use **Google Chrome** or **MS Edge**
- Ensure that cookies JavaScript and pop-ups are all enabled for the enirety of my.scouting.org.
:::

## Cub Scouts

### Cubmaster and Assistant Cubmaster
  - Classroom/Online; Never expires
  - Hazard Weather Training - Online; Needed to take youth on outdoor adventures; required every 2 years
  - Basic Adult Leader Outdoor Orientation (BALOO) 
    - Classroom; Never expires
 
### Den Leader and Assistant Den Leader
  - Classroom/Online; Never expires
  - Hazard Weather Training - Online; Needed to take youth on outdoor adventures; required every 2 years

### Pack Committee Chair
  - Classroom/Online; Never expires

### Pack Committee Member
  - Classroom/Online; Never expires
  
### New Member's Coordinator
  - Online; Never expires


## Scouts BSA

### Scoutmaster and Assistant

  - Classroom/Online; Never expires
  - Hazard Weather Training 
    - Online; Needed to take youth on outdoor adventures; required every 2 years
  - Introduction to Outdoor Skills (IOLS) 
    - Classroom; Never expires
    
### Troop Committee Chair

  - Classroom/Online; Never expires
  
### Troop Committee Member

  - Classroom/Online; Never expires
  
### Merit Badge Counselor

  - Online; Never expires
  
## Venturing

### Crew Advisor and Associate Crew Advisor 

  - Classroom/Online; Never expires
  
### Hazard Weather Training 
  - Online; Needed to take youth on outdoor adventures; required every 2 years
  
### Crew Committee Chair and Members
 - Classroom/Online; Never expires
 
 
## Hazardous Weather

## ILST/C/S


# Advanced Training

## National Youth Leadership Training

## Wood Badge

# Advanced National Training

